<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateReading2sTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('reading2s', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->dateTime('time');
            $table->decimal('bat_voltage', 3,1);
            $table->longText('cmd_2101');
            $table->longText('cmd_2102');
            $table->longText('cmd_2103');
            $table->longText('cmd_2104');
            $table->longText('cmd_2105');
            $table->longText('soc');
            $table->string('rpm');
            $table->longText('soc_bms');
            $table->longText('acp');
            $table->longText('adp');
            $table->longText('battery_current');
            $table->longText('battery_voltage');
            $table->longText('BatTmpMX');
            $table->longText('BatTmpMI');
            $table->longText('bmt1');
            $table->longText('bmt2');
            $table->longText('bmt3');
            $table->longText('bmt4');
            $table->longText('bmt5');
            $table->longText('BatTmpIN');
            $table->longText('MXCV');
            $table->longText('MICV');
            $table->longText('MXCVno');
            $table->longText('MICVno');
            $table->longText('fan_status');
            $table->longText('fan_fbsignal');
            $table->longText('obdabv');
            $table->longText('ccc');
            $table->longText('cdc');
            $table->longText('ccp');
            $table->longText('cdp');
            $table->longText('cot');
            $table->longText('icv');
            $table->longText('ir');
            $table->longText('BatTmpMX2');
            $table->longText('BatTmpMI2');
            $table->longText('bmt6');
            $table->longText('bmt7');
            $table->longText('bmt8');
            $table->longText('bmt9');
            $table->longText('bmt10');
            $table->longText('acp2');
            $table->longText('adp2');
            $table->longText('bcvd');
            $table->longText('qcns');
            $table->longText('abwd');
            $table->longText('bht1');
            $table->longText('bht2');
            $table->longText('soh');
            $table->longText('mdc');
            $table->longText('md');
            $table->longText('midc');
            $table->longText('bcv1');
            $table->longText('bcv2');
            $table->longText('bcv3');
            $table->longText('bcv4');
            $table->longText('bcv5');
            $table->longText('bcv6');
            $table->longText('bcv7');
            $table->longText('bcv8');
            $table->longText('bcv9');
            $table->longText('bcv10');
            $table->longText('bcv11');
            $table->longText('bcv12');
            $table->longText('bcv13');
            $table->longText('bcv14');
            $table->longText('bcv15');
            $table->longText('bcv16');
            $table->longText('bcv17');
            $table->longText('bcv18');
            $table->longText('bcv19');
            $table->longText('bcv20');
            $table->longText('bcv21');
            $table->longText('bcv22');
            $table->longText('bcv23');
            $table->longText('bcv24');
            $table->longText('bcv25');
            $table->longText('bcv26');
            $table->longText('bcv27');
            $table->longText('bcv28');
            $table->longText('bcv29');
            $table->longText('bcv30');
            $table->longText('bcv31');
            $table->longText('bcv32');
            $table->longText('bcv33');
            $table->longText('bcv34');
            $table->longText('bcv35');
            $table->longText('bcv36');
            $table->longText('bcv37');
            $table->longText('bcv38');
            $table->longText('bcv39');
            $table->longText('bcv40');
            $table->longText('bcv41');
            $table->longText('bcv42');
            $table->longText('bcv43');
            $table->longText('bcv44');
            $table->longText('bcv45');
            $table->longText('bcv46');
            $table->longText('bcv47');
            $table->longText('bcv48');
            $table->longText('bcv49');
            $table->longText('bcv50');
            $table->longText('bcv51');
            $table->longText('bcv52');
            $table->longText('bcv53');
            $table->longText('bcv54');
            $table->longText('bcv55');
            $table->longText('bcv56');
            $table->longText('bcv57');
            $table->longText('bcv58');
            $table->longText('bcv59');
            $table->longText('bcv60');
            $table->longText('bcv61');
            $table->longText('bcv62');
            $table->longText('bcv63');
            $table->longText('bcv64');
            $table->longText('bcv65');
            $table->longText('bcv66');
            $table->longText('bcv67');
            $table->longText('bcv68');
            $table->longText('bcv69');
            $table->longText('bcv70');
            $table->longText('bcv71');
            $table->longText('bcv72');
            $table->longText('bcv73');
            $table->longText('bcv74');
            $table->longText('bcv75');
            $table->longText('bcv76');
            $table->longText('bcv77');
            $table->longText('bcv78');
            $table->longText('bcv79');
            $table->longText('bcv80');
            $table->longText('bcv81');
            $table->longText('bcv82');
            $table->longText('bcv83');
            $table->longText('bcv84');
            $table->longText('bcv85');
            $table->longText('bcv86');
            $table->longText('bcv87');
            $table->longText('bcv88');
            $table->longText('bcv89');
            $table->longText('bcv90');
            $table->longText('bcv91');
            $table->longText('bcv92');
            $table->longText('bcv93');
            $table->longText('bcv94');
            $table->longText('bcv95');
            $table->longText('bcv96');
            $table->longText('pi0_status');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('reading2s');
    }
}
